export const testResponse = {
  count: 18,
  next: 'https://swapi.dev/api/people/?search=B&page=2',
  previous: null,
  results: [
    {
      name: 'Beru Whitesun lars',
      height: '165',
      mass: '75',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '47BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-10T15:53:41.121000Z',
      edited: '2014-12-20T21:17:50.319000Z',
      url: 'https://swapi.dev/api/people/7/',
    },
    {
      name: 'Biggs Darklighter',
      height: '183',
      mass: '84',
      hair_color: 'black',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '24BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: ['https://swapi.dev/api/films/1/'],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/12/'],
      created: '2014-12-10T15:59:50.509000Z',
      edited: '2014-12-20T21:17:50.323000Z',
      url: 'https://swapi.dev/api/people/9/',
    },
    {
      name: 'Obi-Wan Kenobi',
      height: '182',
      mass: '77',
      hair_color: 'auburn, white',
      skin_color: 'fair',
      eye_color: 'blue-gray',
      birth_year: '57BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/20/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: ['https://swapi.dev/api/vehicles/38/'],
      starships: [
        'https://swapi.dev/api/starships/48/',
        'https://swapi.dev/api/starships/59/',
        'https://swapi.dev/api/starships/64/',
        'https://swapi.dev/api/starships/65/',
        'https://swapi.dev/api/starships/74/',
      ],
      created: '2014-12-10T16:16:29.192000Z',
      edited: '2014-12-20T21:17:50.325000Z',
      url: 'https://swapi.dev/api/people/10/',
    },
    {
      name: 'Chewbacca',
      height: '228',
      mass: '112',
      hair_color: 'brown',
      skin_color: 'unknown',
      eye_color: 'blue',
      birth_year: '200BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/14/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/3/'],
      vehicles: ['https://swapi.dev/api/vehicles/19/'],
      starships: [
        'https://swapi.dev/api/starships/10/',
        'https://swapi.dev/api/starships/22/',
      ],
      created: '2014-12-10T16:42:45.066000Z',
      edited: '2014-12-20T21:17:50.332000Z',
      url: 'https://swapi.dev/api/people/13/',
    },
    {
      name: 'Jabba Desilijic Tiure',
      height: '175',
      mass: '1,358',
      hair_color: 'n/a',
      skin_color: 'green-tan, brown',
      eye_color: 'orange',
      birth_year: '600BBY',
      gender: 'hermaphrodite',
      homeworld: 'https://swapi.dev/api/planets/24/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
      ],
      species: ['https://swapi.dev/api/species/5/'],
      vehicles: [],
      starships: [],
      created: '2014-12-10T17:11:31.638000Z',
      edited: '2014-12-20T21:17:50.338000Z',
      url: 'https://swapi.dev/api/people/16/',
    },
    {
      name: 'Boba Fett',
      height: '183',
      mass: '78.2',
      hair_color: 'black',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '31.5BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/10/',
      films: [
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/5/',
      ],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/21/'],
      created: '2014-12-15T12:49:32.457000Z',
      edited: '2014-12-20T21:17:50.349000Z',
      url: 'https://swapi.dev/api/people/22/',
    },
    {
      name: 'Bossk',
      height: '190',
      mass: '113',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'red',
      birth_year: '53BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/29/',
      films: ['https://swapi.dev/api/films/2/'],
      species: ['https://swapi.dev/api/species/7/'],
      vehicles: [],
      starships: [],
      created: '2014-12-15T12:53:49.297000Z',
      edited: '2014-12-20T21:17:50.355000Z',
      url: 'https://swapi.dev/api/people/24/',
    },
    {
      name: 'Lobot',
      height: '175',
      mass: '79',
      hair_color: 'none',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '37BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/6/',
      films: ['https://swapi.dev/api/films/2/'],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-15T13:01:57.178000Z',
      edited: '2014-12-20T21:17:50.359000Z',
      url: 'https://swapi.dev/api/people/26/',
    },
    {
      name: 'Ackbar',
      height: '180',
      mass: '83',
      hair_color: 'none',
      skin_color: 'brown mottle',
      eye_color: 'orange',
      birth_year: '41BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/31/',
      films: ['https://swapi.dev/api/films/3/'],
      species: ['https://swapi.dev/api/species/8/'],
      vehicles: [],
      starships: [],
      created: '2014-12-18T11:07:50.584000Z',
      edited: '2014-12-20T21:17:50.362000Z',
      url: 'https://swapi.dev/api/people/27/',
    },
    {
      name: 'Nien Nunb',
      height: '160',
      mass: '68',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'black',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/33/',
      films: ['https://swapi.dev/api/films/3/'],
      species: ['https://swapi.dev/api/species/10/'],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/10/'],
      created: '2014-12-18T11:26:18.541000Z',
      edited: '2014-12-20T21:17:50.371000Z',
      url: 'https://swapi.dev/api/people/31/',
    },
  ],
};
